language: node_js
node_js:
  - '0.10'
env:
  global:
    - PLACEHOLDER: 'Fix the bug that requires this placeholder to add entries to this list!'
    - secure: Q9u7QJnoPaQJUyOsulbalCWx6cMA+tqEv99az31Vst8er2xzp8pav14l5g9iuXFQeldMlk7exZYAwiB6+m5YEqrR4vvobJF5XFlV57afcjKl3VXt/qiz8n9VfTi84UJVszhBGHgFFLSXCcfOhxc2gyqQ1l8uOXqs4ofBOfVJFsWtU+7rLfrs1LrXJtIkLIBQbU6PEOEkalqN5Iybnv8zIHxLvW1CMjxfQ4nVLVd7Bo76L20V1ozBteN41me0U7jb1YE4/jsIIc7Yn97uXBndDXvrLUTBWe3z/HGvX/VwsPXGjWIysTVVm2G0zvEvYJGNq1kwjmYzJEwUVy/Fn2j2SNs1YLveuq3o58Jd9oZVgscob+wXWNtH7Dd/nZspg0u5MEBw+QGB/NdpM4SWQIC02DD6ZEgk2ADAjqXfM2i6qN37RdbaklJq0WHrKaeYjEhpNl77rOnDLarwBKix/umQxSz+tOkradQHMLhRunoynFWkzN+i1hQ85w0P6YGZZj/2z3EJN0W7xrCUzvx5Dhp5GS+6a7aRfn9RIXXEem5Z/SuAQtGFvMC/xJJVtfWp1BXZGErYVrQaO0TMBxrxs66H4QglSWWVVvhBYH49oAcJOG2toZhgHLCsX9sSUPIOmU5cOG1BZDMlQhhylHkEOlZfo3gcAmA4E9wWhKyiN9cojUE=
    - secure: cWZaPT7WHZ2r+zhP4hdAok5uaK6HOfK9YCPhIxbcbLPId8dhNwLmL6X5tZJ6NAEuXfTAOH5DYphhyZ1CIBZ4+b4tVLNzrPjhmP+jRFi8MfvlHBihcuqGBKvBzvAM2OWdYImTi6nMIb5LDer4OVJL1gGuNimi8YEp+4ncavw4Vnc2cY74BdumAJf0lJ40HdTRlvlWa6Aa9u9p54n1ToXRMh0Guf1ANTiXmrAMM7LBSnxvUximhyhsxfvfh7Ax02RQni71PyTfG6gLi8QHAfZDSqVK7Jxt82WqDQlUr3ebPjAP0B9yvlpGiRbtFVYg5Kq4LpKcYhax7On0Xc06jJpVcy5rBkGWdyBWp/U2OBYCPOzv+j/5EGAJcmFrdKkwDUlcPkNFm5sWYE+u8Z4E18fIddid5A4HqVTIXxuLztOTLicYt/HT6JDDgHsi6I3rhVlObuyqMjTJy1NQX/5wPewnH2m9fyDLs0SO2ncLz+SiKexjS63kYLNn3IeIJeFr4c6bgaLERclaNUOSEsTYj7V0xJsfrFMirkzjZKxFHr9x30JETcrkhXheHkKmQKfl53zN76cr1E20FcXIyIlw+P0R5abO8tS7w7eRvRg1ErA12bxXrvB+znGXUyk9edlciLIaO9UNCf4RXCA1r729zainOL4BCUSTtSV/EIzyxqOb+Ug=
install: npm install
before_script:
  - 'git config --global user.name "Travis-CI"'
  - 'git config --global user.email "myk@mykzilla.org"'
script: gulp build
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && gulp deploy'
